### ISSUE TITLE
How to use the CLI in GitLab?

### ISSUE THREAD

**Issue by jz222** [rainforestapp/rainforest-cli#447]
Hi,

we are planning to move our frontend tests to Rainforest. Before we do so, we would like to understand if and how we can use the CLI with GitLab Runners. We would like to achieve something similar to the [example](https://github.com/rainforestapp/ci-sample/blob/develop/.github/workflows/release.yml) you provided for GitHub.

Unfortunately, there aren't any examples for GitLab. Does that mean GitLab is not supported?

**Comment by magni-** [comment]
Hi @jz222 

You're right that we don't currently have an example configuration for GitLab. That said, we have a number of customers who are kicking off Rainforest runs from GitLab, so it's very much supported.

You have two options for using the CLI on GitLab Runners:
1. Install the CLI manually. See the README for details: https://github.com/rainforestapp/rainforest-cli#installation
2. Use our Docker image (`gcr.io/rf-public-images/rainforest-cli:latest`) which comes with the CLI preinstalled. See the GitLab docs: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#define-image-and-services-in-configtoml

The GitHub example you linked explains how to use our GitHub Action, which is a wrapper around the CLI. For something more comparable to GitLab where you'll be using the CLI directly, see the [Travis CI example](https://github.com/rainforestapp/ci-sample/blob/6a93706ce781e4a4b4fc23ded448d6c8aae4c405/.travis.yml#L12-L20) instead:
```yaml
# https://github.com/rainforestapp/ci-sample/blob/6a93706ce781e4a4b4fc23ded448d6c8aae4c405/.travis.yml#L12-L20

- stage: run_rainforest_tests
  script:
  # Install the latest stable version of rainforest-cli.
  # This will allow us to trigger a Rainforest run before we deploy.
  - curl https://api.github.com/repos/rainforestapp/rainforest-cli/releases/latest | jq -r '.assets[].browser_download_url' | grep linux-amd64 | xargs wget -O rainforest-cli.tgz
  - tar xvf rainforest-cli.tgz
  - sudo mv rainforest /usr/local/bin/rainforest
  # Trigger Rainforest run and wait for results
  - /usr/local/bin/rainforest run --run-group 7597 --token $RAINFOREST_TOKEN
```
